// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"; 
import "./globals.css";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" }); // variable for the font

// add meta
export const metadata: Metadata = {
  title: "Personal Budget Tracker", // page title - shown in tab
  description: "Personal budgeting dashboard built with Next.js", // meta description 
  keywords: ['Personal Budget', 'Personal Finance', 'How to manage personal finance'], // seo - keywords
  
};

export default function RootLayout({ children }: { children: React.ReactNode;}) {
  return (
    <html lang="en" className={geist.variable}>
      <body className="min-h-screen bg-slate-100 text-slate-900 antialiased font-sans">
        {/* Background accent */}
        <div className="fixed inset-0 pointer-events-none">
          <div className="absolute -top-40 -right-24 h-80 w-80 rounded-full bg-emerald-200 opacity-40 blur-3xl" />
          <div className="absolute -bottom-40 -left-24 h-80 w-80 rounded-full bg-sky-200 opacity-40 blur-3xl" />
        </div>

        {/* Main app shell */}
        <div className="relative z-10 flex min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}








// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Personal Budget Tracker",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
